name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      # Map GitHub Secrets to env vars
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MAIL_PORT: ${{secrets.MAIL_PORT}}
      MAIL_HOST: ${{secrets.MAIL_HOST}}
      MAIL_USER: ${{secrets.MAIL_USER}}
      MAIL_PASS: ${{secrets.MAIL_PASS}}
      MAIL_FROM: ${{secrets.MAIL_FROM}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4 # Installs pnpm
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build
